env:
  global:
    - CC_TEST_REPORTER_ID=a2c04c8e76935f673eb91042f9a19d37d03bc74940956beec70b7d9386cb43f1
language: node_js
os: windows
node_js:
  - "10"
  - "12"
  - "14"
jobs:
  include:
    - os: osx
      osx_image: xcode12.2
      node_js: 14
    - os: linux
      dist: bionic
      node_js: 14
      addons:
        apt:
          sources:
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
            key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages:
          - clang-9
install:
  - npm install
script:
  - npm run coverage
git:
  depth: 10