env:
  global:
    - CC_TEST_REPORTER_ID=a2c04c8e76935f673eb91042f9a19d37d03bc74940956beec70b7d9386cb43f1
sudo: false
language: node_js
os:
  - linux
  - osx
  - windows
cache:
  directories:
    - coverageResults
node_js:
  - "4"
  - "6"
  - "8"
  - "10"
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
install:
  - npm install
script:
  - npm run test
  - npm run coverage
after_script:
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter format-coverage -t lcov -o coverageResults/codeclimate.$TRAVIS_JOB_NUMBER.json coverage/lcov.info; fi # If the tests are succesfull store the results
  - ls coverageResults
jobs:
  include:
    - stage: upload test results
      node_js: 10
      script:
        - ls coverageResults
        - ./cc-test-reporter sum-coverage coverageResults/codeclimate.*.json -p 12           # Sum all coverage parts into coverage/codeclimate.json
        - ./cc-test-reporter upload-coverage                                                # Upload coverage/codeclimate.json
git:
  depth: 10